#!/usr/bin/env sh

set -xe

pip install \
    --index-url https://download.pytorch.org/whl/cu118 \
    torch \
    torchvision \
    torchaudio

pip install \
    ipython \
    transformers \
    accelerate \
    bitsandbytes \
    optimum \
    diffusers \
    xformers \
    invisible_watermark

pip install spacy

python -m spacy download en_core_web_sm

pip install faster_whisper

pip install soundfile librosa

pip install imgbeddings

