[project]
name = "pyai"
version = "0.1.0"
description = "Add a short description here"
authors = ["pr <pr>"]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
torchaudio = ">=2.2.1,<2.3"
torchvision = ">=0.17.1,<0.18"
pytorch-cuda = "11.8.*"
pytorch = ">=2.2.1,<2.3"
