# theme = "base16_transparent"
theme = "vim_dark_high_contrast"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
gutters.layout = ["diagnostics","spacer","spacer","diff"]

[editor.lsp]
display-messages = true
